//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoontrolBuisnesTile.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.WorkTraffic = new HashSet<WorkTraffic>();
        }
    
        public int IDEmployee { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public int IDBusy { get; set; }
        public string PassSeries { get; set; }
        public string PassNumber { get; set; }
        public int IDSpec { get; set; }
        public int IDGender { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }

        public string FIO { get => $"{LName} {FName} {MName}"; }
    
        public virtual Busyness Busyness { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Specialization Specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTraffic> WorkTraffic { get; set; }
    }
}
