//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoontrolBuisnesTile.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTraffic
    {
        public int IDWorkTraffic { get; set; }
        public int IDEmployee { get; set; }
        public System.DateTime StrartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
